# Generated by Django 3.2.7 on 2021-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='NAME')),
                ('phonenum', models.CharField(max_length=20, verbose_name='PHONE')),
            ],
        ),
    ]
