# Generated by Django 3.2.7 on 2021-09-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_phone_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phonenum',
            field=models.CharField(max_length=20, unique=True, verbose_name='PHONENUM'),
        ),
    ]
