# Generated by Django 3.2.7 on 2021-10-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_alter_phone_phonenum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ('name', 'phonenum')},
        ),
    ]
