# Generated by Django 3.2.7 on 2021-09-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='NAME')),
                ('phonenum', models.CharField(max_length=20, verbose_name='PHONENUM')),
                ('email', models.CharField(max_length=70, verbose_name='EMAIL')),
                ('group', models.CharField(max_length=50, unique=True, verbose_name='GROUP')),
                ('company', models.CharField(max_length=50, unique=True, verbose_name='COMPANY')),
            ],
        ),
    ]
