# Generated by Django 3.2.7 on 2021-09-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecard',
            name='company',
            field=models.CharField(max_length=50, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='group',
            field=models.CharField(max_length=50, verbose_name='GROUP'),
        ),
    ]
