# Generated by Django 3.2.7 on 2021-09-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0002_auto_20210922_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecard',
            name='email',
            field=models.CharField(max_length=70, unique=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='phonenum',
            field=models.CharField(max_length=20, unique=True, verbose_name='PHONENUM'),
        ),
    ]
