# Generated by Django 3.2.7 on 2021-09-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0003_auto_20210922_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namecard',
            options={'ordering': ('group', 'name')},
        ),
        migrations.RemoveField(
            model_name='namecard',
            name='phonenum',
        ),
        migrations.AddField(
            model_name='namecard',
            name='tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='MOBILE'),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='NAME'),
        ),
    ]
