# Generated by Django 3.2.7 on 2021-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0004_auto_20210922_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='namecard',
            name='tel',
            field=models.CharField(max_length=50, unique=True, verbose_name='MOBILE'),
        ),
    ]
