# Generated by Django 3.2.7 on 2021-09-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0005_auto_20210922_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecard',
            name='company',
            field=models.CharField(blank=True, max_length=50, verbose_name='COMPANY'),
        ),
    ]
