# Generated by Django 3.2.7 on 2021-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0006_alter_namecard_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecard',
            name='tel',
            field=models.CharField(max_length=50, verbose_name='MOBILE'),
        ),
    ]
