# Generated by Django 3.2.7 on 2021-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0009_alter_namecard_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecard',
            name='tel',
            field=models.CharField(max_length=50, unique=True, verbose_name='MOBILE'),
        ),
    ]
