# Generated by Django 3.2.7 on 2021-09-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentnum', models.CharField(max_length=10, verbose_name='STUDENTNUM')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('department', models.CharField(max_length=20, verbose_name='DEPARTMENT')),
                ('tel', models.CharField(max_length=50, verbose_name='MOBILE')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='EMAIL')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='ADDRESS')),
            ],
        ),
    ]
